spring:
  datasource:
    url: jdbc:h2:mem:memdb
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: false
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true
    show-sql: true
spring.main.allow-circular-references: true